import Link from 'next/link';
import Image from 'next/image';
import { FC, ReactNode } from 'react';
import { logo } from '../public/assets';
import { useRouter } from 'next/router';

interface LayoutProps {
  children: ReactNode;
}

const Layout: FC<LayoutProps> = ({ children }) => {
  const router = useRouter();
  const { pathname } = router;

  return (
    <>
      <header className='w-full flex justify-between items-center bg-white sm:px-8 px-4 py-4 border-b border-b-[#e6ebf4]'>
        <Link href={'/'}>
          <Image
            src={logo}
            alt='logo'
            width={100}
            height={50}
            className='w-28 object-contain'
          />
        </Link>
        <Link
          href={'/createPost'}
          className='font-medium bg-indigo-500 text-white px-4 py-2 rounded-md'
        >
          Create
        </Link>
      </header>
      <main
        className='sm:p-8 px-4 py-8 w-full bg-[#f9fafe] h-full min-h-[calc(100vh-73px)]'
      >
        <div className='max-w-7xl mx-auto'>
          <h1 className='font-extrabold text-zinc-950 text-3xl'>
            The Community Showcase
          </h1>
          <p className='mt-2 text-gray-400 text-sm max-w-[700px]'>
            {
              pathname === '/' ?
                'Browse through a collection of imaginative and visually stunning images generated by DALL-E AI'
                :
                'Create imaginative and visually stunning images through DALL-E AI and share them with the community'
            }
          </p>
        </div>
        {children}
      </main>
    </>
  );
};

export default Layout;